name: Pod-Merge Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Bundler
      run: gem install bundler
    - name: Install Bundle
      working-directory: ./PodMergeExample
      run: bundle install --jobs 4 --retry 3
    - name: Cleanup
      working-directory: ./PodMergeExample
      run: |
        rm -rf Pods
        rm -rf MergedPods
    - name: Execute Pod Merge
      working-directory: ./PodMergeExample
      run: bundle exec pod install
    - name: Test MergeFile.lock
      working-directory: ./PodMergeExample/MergedPods
      run: if grep -q "c6594f80135b8f8a37f7aa0d49c38b38" MergeFile.lock; then echo "Success"; else exit 1; fi
    - name: Test Podspec for AlamofireGroup Group
      working-directory: ./PodMergeExample/MergedPods/AlamofireGroup
      run: cmp --silent AlamofireGroup.podspec ../../../.github/test_podspecs/AlamofireGroup.podspec
    - name: Test Podspec for MergedSwiftPods Group
      working-directory: ./PodMergeExample/MergedPods/MergedSwiftPods
      run: cmp --silent MergedSwiftPods.podspec ../../../.github/test_podspecs/MergedSwiftPods.podspec
    - name: Test Podspec for Networking Group
      working-directory: ./PodMergeExample/MergedPods/Networking
      run: cmp --silent Networking.podspec ../../../.github/test_podspecs/Networking.podspec
    - name: Test Podspec for UI Group
      working-directory: ./PodMergeExample/MergedPods/UI
      run: cmp --silent UI.podspec ../../../.github/test_podspecs/UI.podspec
    - name: Build Project
      working-directory: ./PodMergeExample
      run: xcodebuild -workspace PodMergeExample.xcworkspace -scheme PodMergeExample -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3" | xcpretty
      
